export default {
    GET_PRODUCT_BEGIN: "GET_PRODUCT_BEGIN",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

    POST_PRODUCT_BEGIN: "POST_PRODUCT_BEGIN",
    POST_PRODUCT_SUCCESS: "POST_PRODUCT_SUCCESS",
    POST_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

    EDIT_PRODUCT_BEGIN: "EDIT_PRODUCT_BEGIN",
    EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_FAILURE: "EDIT_PRODUCT_FAILURE",

    DELETE_PRODUCT_BEGIN: "DELETE_PRODUCT_BEGIN",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",

    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES"

}